# Generated by Django 4.2.2 on 2023-08-10 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_team_lastupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_code', models.TextField()),
                ('language', models.CharField(choices=[('python', 'py'), ('cpp', 'c'), ('c', 'c')], max_length=10)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
            ],
        ),
    ]
