# Generated by Django 4.2.2 on 2023-08-10 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_team_islogin_alter_submission_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='lastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 17, 10, 52, 116049)),
        ),
    ]
